### ISSUE TITLE
windows10:failed to execute script main

### ISSUE THREAD

**Issue by Joagee** [QIN2DIM/V2RayCloudSpider#14]
windows10:failed to execute script main

**Comment by QIN2DIM** [comment]
用来部署项目的学生机过期了- -问题已解决

**Comment by QIN2DIM** [comment]
目前最新版本的panel软件写死了握手主机的ip，然而运行master的服务器过期了，暂时失联了(´இ皿இ｀)…这两天我会把更新了ip表的软件重新发布

**Comment by QIN2DIM** [comment]
（顺带优化一下软件性能）

**Comment by chen-jingliang** [comment]
我也遇到了相同的问题，这是一个好软件，期待早日更新

**Comment by QIN2DIM** [comment]
服务器已重新上线，通过panel可以访问链接池了~
但是采集队列还需维护，数量和质量都还有待提升。
