### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by hecheng6971** [QIN2DIM/V2RayCloudSpider#16]
为什么更新不了最新版本

**Comment by QIN2DIM** [comment]
从README中获取的panel就是目前发行版软件的最新版本v-4.5.2

**Comment by QIN2DIM** [comment]
若panel抛出“需更新到最新版本软件”的警告，也许是软件运行过程中出现了异常。可能原因有链接池为空或是接口暂时关闭（造成的握手超时异常）。
