### ISSUE TITLE
客户端4.5.2，提示有新版需更新，但这里还是4.5.2，没新版呢？

### ISSUE THREAD

**Issue by LvDeShei** [QIN2DIM/V2RayCloudSpider#26]
提示更新：https://github.com/QIN2DIM/V2RayCloudSpider

**Comment by QIN2DIM** [comment]
> 目前开源版本最新版本号是`v4.5.2`（因为没有小伙伴提新的需求，就没更新Orz）

如果确定使用的客户端是最新版，一顿操作后弹出“更新提示”，可能是**软件针对某些特定的用户行为做出的统一回复**，既 ”更新版本”。

这里的特定异常一般是**网络状况不佳**或**申请了不在订阅池中的订阅**。

如果不是上述情况，方便分享一下出现异常的操作步骤bo~我康康。

**Comment by QIN2DIM** [comment]
> 提示更新：https://github.com/QIN2DIM/V2RayCloudSpider

目前开源版本最新版本号是v4.5.2

这里的特定异常一般是**网络状况不佳**或**申请了不在池中的订阅**。

**Comment by QIN2DIM** [comment]
> 提示更新：https://github.com/QIN2DIM/V2RayCloudSpider

截止2021.07.18，最新开源版本号是v4.5.2

这里的特定异常一般是**网络状况不佳**或**申请了不在池中的订阅**。

**Comment by LvDeShei** [comment]
明白了，感谢！
