### ISSUE TITLE
萌新疑惑

### ISSUE THREAD

**Issue by shiguangwl** [QIN2DIM/V2RayCloudSpider#37]
为什么要分个单独的前端exe,而不直接搞个订阅接口?
例如v2ray订阅地址直接填写接口地址.后端吧订阅链接内容传给用户
这不很方便么~

**Comment by beiyuouo** [comment]
很简单的啦，防止滥用

**Comment by QIN2DIM** [comment]
这个`.exe`前端仅仅是个用于demo演示的`panel`。至于为什么会有这个东西是有历史遗留原因的233。当时项目开工的时候对整个代理生态并不是很了解，想做个能代理流量的`Windows`客户端来着，后来发现自己太naive了，但demo也实现了部分功能就索性发布使用了。

关于接口地址的融合问题，之前有设计过`webhook`映射，但为了防止滥用也没开放使用。不过，我们后来将订阅转发的功能封装到了聊天机器人里。

**Comment by QIN2DIM** [comment]
@shiguangwl 
我们将“订阅接口”嵌入了多个平台的聊天机器人中，如：Telegram、钉钉、QQ
具体可参照[→ Issue#9](https://github.com/QIN2DIM/V2RayCloudSpider/issues/9#issuecomment-908506009)
若无其他疑问，本Issue即将关闭
