### ISSUE TITLE
萌新想问一下大神，想实现简单的采集订阅地址的功能，只依赖Python可以吗？

### ISSUE THREAD

**Issue by zakizou** [QIN2DIM/V2RayCloudSpider#38]

**Comment by QIN2DIM** [comment]
昂，采集器流量没过代理端口，IP裸奔，被各大机场主联合绞杀了喵(可能是永久ban233)！不过这是小事，稍后我重启一下demo就好了。

**Comment by zakizou** [comment]
萌新想问一下大神，想实现简单的采集订阅地址的功能，只依赖Python可以吗？看了你的

**Comment by QIN2DIM** [comment]
> 萌新想问一下大神，想实现简单的采集订阅地址的功能，只依赖Python可以吗？

(⁎⁍̴̛͂▿⁍̴̛͂⁎)*✲ﾟ*没听明白…可你稍微解释下吗

**Comment by zakizou** [comment]
> 
> 
> > 萌新想问一下大神，想实现简单的采集订阅地址的功能，只依赖Python可以吗？
> 
> (⁎⁍̴̛͂▿⁍̴̛͂⁎)_✲ﾟ_没听明白…可你稍微解释下吗
就是只执行采集的代码，输入订阅地址。手动执行一次出一次结果。而不进行封装这些。

**Comment by QIN2DIM** [comment]
>  就是只执行采集的代码，输入订阅地址。手动执行一次出一次结果。而不进行封装这些。

@zakizou 整个代码架构本就是基于微服务的思路设计的（虽然在当前开源版本上来看仍有不少冗余），所以原则上采集器的原子节拍必须实现一轮transaction（通俗讲手动执行一次必须有相应的数据库接收采集器的输出，也就是订阅地址）。但仍可以通过扁平接口控制实例的具体业务行为，如果小伙伴并不知道怎么玩redis，只想通过鼓捣py代码实现如你所述的简单需求当然也是可以的。如果需要的话我可以发一个example

**Comment by zakizou** [comment]
> 
> 
> > 就是只执行采集的代码，输入订阅地址。手动执行一次出一次结果。而不进行封装这些。
> 
> @zakizou 整个代码架构本就是基于微服务的思路设计的（虽然在当前开源版本上来看仍有不少冗余），所以原则上采集器的原子节拍必须实现一轮transaction（通俗讲手动执行一次必须有相应的数据库接收采集器的输出，也就是订阅地址）。但仍可以通过扁平接口控制实例的具体业务行为，如果小伙伴并不知道怎么玩redis，只想通过鼓捣py代码实现如你所述的简单需求当然也是可以的。如果需要的话我可以发一个example

如果大神有空的话，那就谢谢了。

**Comment by QIN2DIM** [comment]
@zakizou 
如果可以的话请小伙伴描述一下具体的需求，比如使用场景，开发环境等等。
有条件的话可以加一下交流群细聊，或者发在这也行。我根据具体情况设计一下运行实例 ୧⍢⃝୨

**Comment by zakizou** [comment]
> 
> 
> @zakizou
> 如果可以的话请小伙伴描述一下具体的需求，比如使用场景，开发环境等等。
> 有条件的话可以加一下TG交流群细聊，或者发在这也行。我会根据你的具体情况设计一下运行实例 ୧⍢⃝୨

想来还是不浪费大神时间了，我自己去琢磨技术文档搭建吧，感谢耐心回答。

**Comment by QIN2DIM** [comment]
@zakizou 
技术文档快一年多没更新了，小心被我“坑”到哈哈哈（小脸一红）

**Comment by QIN2DIM** [comment]
- [ ] 使用 Hugo 重写/移植技术文档
  - [ ] Overview
  - [ ] WHAT V2RayCloudSpider
  - [ ] WHY V2RayCloudSpider
  - [ ] How V2RayCloudSpider
    - [ ] How it works
    - [ ] How to run the V2RayCloudSpider in your machine
  - [ ] Conclusion
  - [ ] Reference
- [ ] 提供 基于Windows/Linux（CentOS7）白环境的一键安装脚本
