### ISSUE TITLE
ssr怎么全都订阅失败啊，多复制几个就被冻结

### ISSUE THREAD

**Issue by g123y456j** [QIN2DIM/V2RayCloudSpider#4]

**Comment by QIN2DIM** [comment]
emm，从[查看订阅]里面挑选ssr链接看看

**Comment by QIN2DIM** [comment]
小伙伴问题解决了吗，如有问题请及时反馈~~

**Comment by g123y456j** [comment]
> 小伙伴问题解决了吗，如有问题请及时反馈~~

多试试也有能用的，一般时间比较近的能用的概率略高点，2月多到期的基本都不行。大佬加油整治整治
