### ISSUE TITLE
[Hamster]windows client 查看可用连接

### ISSUE THREAD

**Issue by wanghaisheng** [QIN2DIM/V2RayCloudSpider#46]
订阅类型后面跟着一串GUID样子的字符串 这个是否替换成url更加直观 更加方便用户选择
我使用了一段时间 想优先选择之前使用的provider

**Comment by QIN2DIM** [comment]
盲猜 100G 6day， 我也觉得香...速度还快的不行

**Comment by QIN2DIM** [comment]
> 想优先选择之前使用的provider

format 有推荐吗，还是直接码域名

**Comment by wanghaisheng** [comment]
感觉马域名就挺好的xxx.com 这种

**Comment by QIN2DIM** [comment]
#47 @wanghaisheng

**Comment by QIN2DIM** [comment]
擦，为什么用 Pyinstaller 打包的单体程序启动这么慢，我以为是代码的问题。

**Comment by wanghaisheng** [comment]
haha  没有用它打包过 回头我也试试
