### ISSUE TITLE
节点显示还有有效期，实际已经过期，请大神解决

### ISSUE THREAD

**Issue by chen-jingliang** [QIN2DIM/V2RayCloudSpider#5]
节点显示还有3-5天的有效时间，可是测试后实际已经过期，请大神解决时间判断的问题。有的节点显示还有半个月，可是全是过期的，不知时间为什么判断不准？

**Comment by QIN2DIM** [comment]
这个问题我也发现了，正在处理。
具体原因是 池内链接的过期时间是以  发现机场时的优惠政策为准的（而非热数据），当前版本程序在运行过程中不会再次审核机场的优惠政策。也就是说如果程序初始化时链接可用30天，那么之后所有从该机场获取的链接都默认为30天失效，而在此期间该机场的优惠政策随时可能调整（比如由原先30天变为仅1天可用），这就导致了如题发生的bug。

**Comment by chen-jingliang** [comment]
感谢大神提供思路独特的产品，期待早日解决准确判断时间的问题
