### ISSUE TITLE
[BUG]down?

### ISSUE THREAD

**Issue by wanghaisheng** [QIN2DIM/V2RayCloudSpider#55]
**描述您遇到的问题**
对 bug 的清晰而简洁的描述。

**如何重现问题**
把你遇到的问题的发生步骤替换掉下面的内容：

**期待修复的效果**
清晰而简洁地描述您期望的修复效果。

**相关截图**
若有必要，可以用相关截图来增加信息浓度。

**环境版本说明**
 - 操作系统 [e.g. Windows]
 - 板载方案 [e.g. v2rayN, Qv2ray]
 - 软体版本 [e.g. v4.5.4]

**附加内容**
添加您认为有必要补充的内容。

又挂了？

**Comment by QIN2DIM** [comment]
今把服务停了一下（然后忘记开了

**Comment by wanghaisheng** [comment]
@QIN2DIM 又崩了？
