### ISSUE TITLE
貌似数据库被人不停删库, 链接全没了

### ISSUE THREAD

**Issue by x2658y** [QIN2DIM/V2RayCloudSpider#56]

**Comment by QIN2DIM** [comment]
并非。

客户端里写了一点逻辑用于分担集群算力，然而上游定时任务设置的不合理，又因为下游用户量激增，订阅池偶发性”雪崩“。

其次是原先设定的 `pool_cap` 只有 25 - -，真是救大命...实时缓存的订阅数量只维护在20左右的数量上。

来自大陆的同学上网时间作息什么的都有社群规律，所以基本上都是高峰期会集中消耗一波订阅，然后采集器订单量激增，缓存堆积，这会导致下一批订阅的过期时间错不开，就会引起下游用户批量清除过期订阅的被动行为。

根本问题可能在于用户量较多，而可用缓存较少（可能比例是500:1）。我觉得可以回收下游用户清除订阅的权限，或者增加 `pool_cap` 以及调整集群节拍（比如闲时工作，高峰期静默）

**Comment by wanghaisheng** [comment]
无可用订阅吗 @QIN2DIM

**Comment by QIN2DIM** [comment]
> 无可用订阅吗 @QIN2DIM

性能校准的代理池已经推送到TG频道了，还没挂到 GitHub 上
