### ISSUE TITLE
开发者文档我觉得写在“wiki”里比较好

### ISSUE THREAD

**Issue by vanhiupun** [QIN2DIM/V2RayCloudSpider#58]

**Comment by QIN2DIM** [comment]
https://blog.echosec.top/v2rss-docs/zh

类似这样吗

**Comment by vanhiupun** [comment]
是的，加到这个里面就好了https://github.com/QIN2DIM/V2RayCloudSpider/wiki

**Comment by QIN2DIM** [comment]
ok，刚好打算重写技术文档，之前的内容太久了。
