### ISSUE TITLE
feat(remove): v6.x.r-dev 项目计划

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/V2RayCloudSpider#59]
1. **重写项目技术文档** https://github.com/QIN2DIM/V2RayCloudSpider/issues/58

   > 先前的技术文档年久失修，已无参考价值。

   涵盖项目的下载安装介绍，examples 运行示例介绍，脚手架指令介绍，链接采集与获取常用方法介绍，应用部署最佳实践等。

2. **开发脚手架指令 `install`** 

   基于主流操作系统（Windows/MacOS/Ubuntu18.04+）的指令集编写第三方驱动自动下载适配脚本。

3. **制作基于 `pywebio` 编写的 `aff` 协同注册子模块（Optional）**

   该模块继承云彩姬自带的 `synergy` 协同模式以及 `armor` 人机对抗模组，能够以极高的并发率批量生成邀请用户实体并完成实例注册。与其他开源的脚本项目不同，本模块内联 `armor` 应用模组，能够穿透几乎所有的基于模式产出的人机对抗验证。

   该模块提供一个简洁的 `web` 面板，仅有一个 Input 元素以及一个 Button 元素。填入带有 `aff` 的分享链接则启动协同注册任务；填入服务注册链接则根据模式自动生成实例摘要信息并启动采集器任务获取订阅。

4. **基于 `Playwright` 修改部分代码提高系统性能（Optional）**

**Comment by wanghaisheng** [comment]
any update

**Comment by QIN2DIM** [comment]
> any update

目前来看这个项目能够持续稳定运行很长时间，上次有效更新至今差不多三个月了。

然后这些开发计划感觉都没啥意思，更新维护这些功能让我感到很无趣。如果有什么好的点子我会持续重构。

**Comment by QIN2DIM** [comment]
云彩姬的订阅池能够自动轮换，也有比较稳定哨兵机制可以对冲宕机风险，不像一些直接贴出节点链接的项目还需要手动推送。现在全自动化的弊端就是- -这些代码久了不看要改动加入新的东西还是需要点时间适应，毕竟代码量不少。

**Comment by wanghaisheng** [comment]
我问个题外话 假如我有一个应用，我想检测请求上来的ip是不是来自SSPanel  或者什么clashx v2ray这种服务商或者节点
本质上这些SSPanel 都是部署在主流的cloud service provider上，我有cloud service provider ip list其实也可以
我如果研究我们的采集程序 能得到这样一个样本库吗

**Comment by wanghaisheng** [comment]
我看了一些其中设计验证码的代码 还算能看懂 也比较有意思哟

**Comment by QIN2DIM** [comment]
> 我看了一些其中设计验证码的代码 还算能看懂 也比较有意思哟

首先我目前知道的所有 SSPanel “开发团队” 都没能力自己做验证码系统，都是依赖第三方人机挑战服务。国外的 FunCaptcha、reCaptcha、hCaptcha 是主流，国内有极验。我通过一些特种搜索引擎看了大概3千多家提供商站点，基本是 reCaptcha 和 极验（滑块）多一些，剩下的都是邮箱验证。这些东西我都研究过一遍了。

**Comment by QIN2DIM** [comment]
> 我问个题外话 假如我有一个应用，我想检测请求上来的ip是不是来自SSPanel 或者什么clashx v2ray这种服务商或者节点 本质上这些SSPanel 都是部署在主流的cloud service provider上，我有cloud service provider ip list其实也可以 我如果研究我们的采集程序 能得到这样一个样本库吗

没懂。。

**Comment by wanghaisheng** [comment]
我想block所有来自中国的用户 ip是第一步，第二步就是这种用代理上来的用户(这个是我上面那一串的本意)

**Comment by wanghaisheng** [comment]
> 

我看chrome插件市场现在已经有一款做hcaptcha破解的

**Comment by QIN2DIM** [comment]
> 我想block所有来自中国的用户 ip是第一步，第二步就是这种用代理上来的用户(这个是我上面那一串的本意)

这是单一节点不可能实现的需求，在想啥呢😂

**Comment by QIN2DIM** [comment]
> 我看chrome插件市场现在已经有一款做hcaptcha破解的

额- -我为啥自己造轮子啊- -不还是因为这些太垃圾了。2captcha是付费服务，我还没试过，但其他市面上已有的插件都很菜。你可以打开浏览器插件访问[测试站点](https://accounts.hcaptcha.com/demo?sitekey=0d4fed78-f5f0-45fc-9ef7-ab6a34923157)看一下它们的表现。但如果你用 `hcaptcha-challenger`，基本上是还来不及看清有啥图挑战就通过了。

**Comment by wanghaisheng** [comment]
你要不要做个插件 赚点油条钱 哈哈 把hcaptcha-challenger封装下

**Comment by QIN2DIM** [comment]
> 你要不要做个插件 赚点油条钱 哈哈 把hcaptcha-challenger封装下

如果要在程序里调用的话，container server 和 pypi 是最佳实践，只有闲的没事干的人才会依靠插件解决人机挑战- -显然是伪需求。
