### ISSUE TITLE
仓库最新的6.0 脚手架的router命令是否未完善？

### ISSUE THREAD

**Issue by shenyanshu** [QIN2DIM/V2RayCloudSpider#60]
今天使用最新的6.0部署，但是在使用router命令的时候，无法启动

**Comment by QIN2DIM** [comment]
功能解耦了没来得及重新发布（拖延症orz）有些接口还在测试，我稍后先发一个可以生产部署的。

**Comment by QIN2DIM** [comment]
已推送。原来的 `router` 指令改成了 `server`指令，接受3个参数， `host`， `port` ，`detach`，都有默认值，`host=127.0.0.1`，`port=22333`，`detach=True`。指定 `detach=False` 时被请求的订阅不会被删除，接口调试时使用。

具体的文档可以看下面的链接，还没完全写完，之后其他服务调整了之后我会再更新-。-

> 链接：https://www.apifox.cn/apidoc/shared-fe514493-d572-461f-894e-8a39375cef05 访问密码：y2WZHeHF

**Comment by shenyanshu** [comment]
非常感谢，我拉取部署一下看看
