### ISSUE TITLE
[Question] 云彩姬无可用订阅

### ISSUE THREAD

**Issue by StaRiveRain** [QIN2DIM/V2RayCloudSpider#61]
你好，我想问一下获取订阅链接显示无可用订阅是怎么回事
![捕获](https://user-images.githubusercontent.com/102610779/161610226-6f2517d9-eea9-42f8-a8b0-9c766750cae7.PNG)

**Comment by faustliang** [comment]
同问，不知道怎么操作

**Comment by QIN2DIM** [comment]
是的，停更一段时间

**Comment by StaRiveRain** [comment]
好的谢谢

**Comment by faustliang** [comment]
👌感谢> 是的，停更一段时间。我会在4月中下旬重新开放服务，如有特殊情况会提前或延后。到时候会使用新编译的客户端。

**Comment by mq123123** [comment]
> 是的，停更一段时间。我会在4月中下旬重新开放服务，如有特殊情况会提前或延后。到时候会使用新编译的客户端。

新的客户端会有新的GUI吗

**Comment by QIN2DIM** [comment]
可以关注 [TG频道](https://t.me/+8Grr6GgsApU5ODQx) 使用灰测版本。GitHub 上老旧的发行客户端不再维护。

**Comment by QIN2DIM** [comment]
> 新的客户端会有新的GUI吗
@mq123123 无需求不更新。
