### ISSUE TITLE
[Question] mac电脑使用问题

### ISSUE THREAD

**Issue by yhuihu** [QIN2DIM/V2RayCloudSpider#62]
能否提供一个mac客户端或者web端方便使用。

**Comment by QIN2DIM** [comment]
暂无 Mac 客户端的开发计划。

为了防止滥用，Web 端也不会引入。

**Comment by QIN2DIM** [comment]
可以加入 [TG交流群](https://t.me/+hPVteWIGnqhlOWJh) 描述具体需求
