### ISSUE TITLE
⚠项目闭源警告

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/V2RayCloudSpider#63]
为减少滥用风险，V2RSS云彩姬上游产出将转为闭源状态（也即 action 不再更新），采集器代码保持落后于开发版半年的进度稳定推送。也请早已熟悉 V2RayCloudSpider 业务逻辑的各路高玩不要将自己手动搜集/编排的 action 分享给其他人，保持自用的需求量运行程序。

**Comment by ufoowan** [comment]
那是以后不能用了嘛。。。

**Comment by QIN2DIM** [comment]
你是说哪个，可以进群交流

**Comment by QIN2DIM** [comment]
你是说哪个，可以进群交流

**Comment by QIN2DIM** [comment]
> 那是以后不能用了嘛。。。

主要还是维护困难，开源版本和闭源使用的项目差距太大了，每次更新我都要 review 一堆代码。

**Comment by nobleiris** [comment]
群是哪个？

**Comment by ufoowan** [comment]
> 你是说哪个，可以进群交流

云彩姬。。 同问组织的群。。。

**Comment by ufoowan** [comment]
> 

闭源的版本怎么获取呀？

**Comment by szzhangtao88** [comment]
闭源的版本怎么获取呀？

**Comment by 1deluyi1** [comment]
这是用不了了吗

**Comment by FairyWorld** [comment]
![image](https://user-images.githubusercontent.com/32956212/169444421-1b043f4b-5be8-44ac-b627-589f774fb5d8.png)

**Comment by FairyWorld** [comment]
![image](https://user-images.githubusercontent.com/32956212/169444455-09dc1e94-7248-4c38-8eb6-aac07148dae4.png)
现在采集不到订阅了是因为闭源了吗?

**Comment by FairyWorld** [comment]
> > 你是说哪个，可以进群交流
> 
> 云彩姬。。 同问组织的群。。。
同问

**Comment by FairyWorld** [comment]
求一个组织
