### ISSUE TITLE
关于软件部署的问题

### ISSUE THREAD

**Issue by numberone0001** [QIN2DIM/V2RayCloudSpider#9]
您好！
看了您的项目，很有帮助。有个问题想咨询啊您：
如果想在本地windows二次开发本项目的话，需要配置哪些地方呢？如何配置呢？也需要像https://shimo.im/docs/5bqnroJYDbU4rGqy/read
这里所写的，把所有服务安装一遍吗？
可以也写个配置教程吗？

**Comment by numberone0001** [comment]
想在自己的设备上跑下您的代码，但是部署不成功。。。目前没有搞明白哪部分代码应该放在服务器端，哪部分放在本地。希望您可以直到下！谢谢！

**Comment by numberone0001** [comment]
或者说，要是想在本地windows二次开发本项目的话，需要配置哪些地方呢？

**Comment by numberone0001** [comment]
另外，项目详情里写的“该项目基于Windows10环境开发”，可并无win10下如何配置开发环境的相应介绍。。。希望开发者予以指导。


Tos：该项目基于Windows10环境开发，Mac用户可能无法正常使用

Help： 环境配置说明

打开冰箱门
请将V2RaycSpider+版本号的源码文件上传至服务器的/qinse文件夹（若没有就新建一个或者改动源码）
请确保部署环境已安装redis并开放远程访问权限
请确保部署环境已配置Python3开发环境且已安装第三方包
# 拉取第三方包
pip install -r /qinse/V2RaycSpider1125/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
将李芬特装入冰箱

全局配置文件：V2RayCloudSpider/config.py at master · QIN2DIM/V2RayCloudSpider (github.com)
关闭冰箱门

程序全局接口：V2RayCloudSpider/main.py at master · QIN2DIM/V2RayCloudSpider (github.com)
balance_scale 参数设置

**Comment by numberone0001** [comment]
你好，我在服务器端按您写的配置方法搭建了环境，可是 https://shimo.im/docs/5bqnroJYDbU4rGqy/read 这里好像没有写出mysql的作用以及配置方法，运行后就出现了下面的错误。您可否指导下呢？

[root@instance-1 V2RaycSpider1125]#  python3 main.py deploy &
[1] 18179
[root@instance-1 V2RaycSpider1125]# Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from BusinessCentralLayer.control import Interface as app
  File "/root/qinse/V2RaycSpider1125/BusinessCentralLayer/control.py", line 11, in <module>
    from BusinessCentralLayer.middleware.subscribe_io import FlexibleDistribute
  File "/root/qinse/V2RaycSpider1125/BusinessCentralLayer/middleware/subscribe_io.py", line 7, in <module>
    from BusinessCentralLayer.middleware.flow_io import FlowTransferStation
  File "/root/qinse/V2RaycSpider1125/BusinessCentralLayer/middleware/flow_io.py", line 4, in <module>
    import pymysql
ModuleNotFoundError: No module named 'pymysql'

**Comment by QIN2DIM** [comment]
oh没想到真有小伙伴想跑一下代码。我一开始还没想着开源代码的（虽然代码是发在那了），因为讲清楚如何部署环境和写技术文档都挺耗时的 毕竟前文也说了是用来刻意练习的练手项目（主要是太懒了），如果想交流技术♂可以来[Telegram Group](https://t.me/joinchat/HlB9SQJubb5VmNU5)

**Comment by QIN2DIM** [comment]
> 这个项目（开源在`Github`上的版本）暂时没有用到MySQL（测试代码忘记删了Orz）。

执行一下pip拉取相关依赖既可，应该是这个库我没有放在`requirement.txt`里

```bash
# 当前目录下执行
pip install pymysql
```

**Comment by QIN2DIM** [comment]
> 另外，项目详情里写的“该项目基于Windows环境开发”，可并无Windows下如何配置开发环境的相应介绍。。。希望开发者予以指导。
> 
> Tos：该项目基于Windows环境开发，Mac用户可能无法正常使用
> 
> Help： 环境配置说明

上文提到的无法可用的场景（目前已知）特指**目录定位**和**程序打包**问题。

### 1. 不同操作系统的路径定位方案不同

对于python `os`库在不同操作系统中的路径定位实现方案不同，根据报错提示改就行。因为`config.py`中出现了`C://XXX`这样的写法……而Linux和Mac是没有这种东西的（但其实只有在某些特殊场景下才会报错）。

### 2. 关于`panel`客户端的打包问题

本人用的是`Pyinstaller`打包桌面程序，这个方案暂时没法（在Windows环境下）稳定地打包`.app`（也可能是我的打开方式有问题）。

**Comment by wanghaisheng** [comment]
如果跨平台的编译比较难，能不能搞个docker文件

**Comment by QIN2DIM** [comment]
> 如果跨平台的编译比较难，能不能搞个docker文件

emmm，是后端服务的docker吗

**Comment by wanghaisheng** [comment]
根据我的理解 mac上没有client 那我要用 就得自己部署一套后台？ 
mac上开发或者适配现有的windows client到mac上去 好像比较难？
我之前在windows上尝试部署过 因为redis的原因后来放弃了

**Comment by QIN2DIM** [comment]
> 根据我的理解 mac上没有client 那我要用 就得自己部署一套后台？

"client": 目前开源版本panel中的“获取订阅链接”功能指向某一确定的redis数据库。这个数据库可以是部署在云的也可以是本机跑的。

显然，如果需要建立自己的redis数据库，是需要“部署一套后台”的。

> mac上开发或者适配现有的windows client到mac上去 好像比较难？

目前的开源版本的“client”是基于python第三方库`easygui`快速搭建的前端面板，理论上并不能实现类似`electron`高度抽象高度封装一套代码就能跨平台维护的需求。比如一些众所周知的“权限问题”以及“上下文目录检索”问题，python中同一处`os.dirname()`返回的结果不一定相同，这也许并不会影响核心功能的正常使用，但会使得系统的运行偏离设计构想，出现不可控的运行结果。

其实在mac上开发并不难（比如针对路径问题，整个路径索引都被配置文件高度支配，只需要改一行代码就可以de了）- -主要是当初缺少mac的测试环境，也没人提issue就没做233- - 

> 我之前在windows上尝试部署过 因为redis的原因后来放弃了

大概去年暑假整个微服务快速扩建的脚本就已经开发好了- -但随着对设计模式的学习逐渐加深，发现当初设计的框架实在naive，就一直没发布- -我也放弃了233，主要是一个在用工具的分享~没人提issue我也没想着放入新的东西

**Comment by QIN2DIM** [comment]
client 和 server 是两个完全分离的项目（至少目前最新开源版本是这样的嗯）

**Comment by QIN2DIM** [comment]
> 我之前在windows上尝试部署过 因为redis的原因后来放弃了

啊刚才看了一下之前写的技术文档，确实需要更新了...

**Comment by wanghaisheng** [comment]
实在不行 client后面弄成bs这种怎么样 挂一个page 流量大还可以赚点ad

**Comment by QIN2DIM** [comment]
> 实在不行 client后面弄成bs这种怎么样 挂一个page 流量大还可以赚点ad

emmmm，当时在技术选型的时候当下比较流行的解决方案都考虑过了，选了一个性价比最高的方案了暂时。

一个是docker这块，因为项目架构实在是太简单了，很难想到哪些模块能切到docker里运行（或许可以制作一个具备所需运行依赖的最小体积镜像），再来是目前团队在用的服务和开源版本的差距还蛮大的，开源版本服务还不是一个完整的薅羊毛生态....“更新采集队列”得手动push仓库才行，还没法“自产自销”。这需要保持一个微妙的平衡...万一薅穿了以后再也不会有免费的policy可用了233

关于client，目前比较可靠的是用聊天机器人分发订阅，其他解决方案相对来说都不太安全；

最后本项目是不可盈利的~

**Comment by wanghaisheng** [comment]
话说 我不用client的话 能在mac上通过post请求后台得到sharelink吗
有api endpoint不

**Comment by QIN2DIM** [comment]
有呀，直接改`viewer`的[flask接口](https://github.com/QIN2DIM/V2RayCloudSpider/blob/master/V2RaycSpider1225/src/BusinessViewLayer/myapp/app.py)`Admin Interface`再部署就行。

虽然没有文档- -但是应该不难操作，接口都写好了，直接访问就能出结果。

**Comment by QIN2DIM** [comment]
> 话说 我不用client的话 能在mac上通过post请求后台得到sharelink吗
> 有api endpoint不
> 
> 我现在要两台机都登录钉钉 然后通过聊天记录共享。。
> @QIN2DIM

其实是有更加一劳永逸的方案的~
![image](https://user-images.githubusercontent.com/62018067/131375098-b0284102-7607-4cb0-97db-00d13df1b87b.png)

**Comment by QIN2DIM** [comment]
> 话说 我不用client的话 能在mac上通过post请求后台得到sharelink吗
> 有api endpoint不
> 
> 我现在要两台机都登录钉钉 然后通过聊天记录共享。。
> @wanghaisheng 

昂刚去吃了波夜宵- -回来看了一下钉钉机器人的文档。

说实话这文档写的真是非常有水平了，而且平台生态十分健壮，搭建一个用于（群组内）分发订阅的机器人门槛非常低（几乎5行代码就能实现消息转发）于是一个[demo](#jump)已经写完了- -[查看运行结果](#demo)

然后是关于`DingTalk`相关代码暂时不会加入到master中，毕竟我也是入门5分钟的新手（此处省略若干字）- -如果小伙伴感兴趣可以参考模板写自己的机器人，如果可以的话建议把`交互安全`以及`异步性能`写到顶（经验之谈）。

**[注意]** 本人对“钉钉开发者平台”的操作略为生疏，所以：
- 以下参考代码可能仅对群组机器人有效？
- 也许不是任何“身份”的“成员”都可以开发机器人？我所生成的`webhook`以及`secret_key`都是以“管理员”身份执行的。


<span id="jump"></span>
## 参考代码
```python
# -*- coding: utf-8 -*-
# Time       : 2021/8/31 2:19
# Author     : QIN2DIM
# Github     : https://github.com/QIN2DIM
# Description:DingTalk bot | V2RCS：分发云彩姬订阅的钉钉机器人

import base64
import hashlib
import hmac
import json
import time
import urllib.parse

import requests


def ding_to_group(subscribe: str = "这里是V2Ray云彩姬",
                  access_token: str = None, timestamp: str = None, sign_: str = None
                  ):
    """
    通过POST接口，传递必要参数，控制指定的机器人向指定的群组发送TEXT类型消息
    :param subscribe: 要发送的订阅
    :param access_token:
    :param timestamp:
    :param sign_:
    :return:
    """
    web_hook = "https://oapi.dingtalk.com/robot/send?"
    headers = {
        "Content-Type": "application/json",
    }
    params = {
        "access_token": access_token,
        "timestamp": timestamp,
        "sign": sign_
    }
    data = {
        "msgtype": "text",
        "text": {"content": subscribe},
    }
    session = requests.session()

    response = session.post(web_hook, headers=headers, params=params, data=json.dumps(data))

    print(response.json())


def calculate_the_signature(secret_key: str = None) -> dict:
    """
    实现机器人安全组接口策略，此处使用官方文档中的案例写法
    :param secret_key:
    :return:
    """
    # 机器人安全密钥
    secret = secret_key

    # 计算时间戳
    timestamp = str(round(time.time() * 1000))

    # 计算签名
    secret_enc = secret.encode('utf-8')
    string_to_sign = '{}\n{}'.format(timestamp, secret)
    string_to_sign_enc = string_to_sign.encode('utf-8')
    hmac_code = hmac.new(secret_enc, string_to_sign_enc, digestmod=hashlib.sha256).digest()
    sign = urllib.parse.quote_plus(base64.b64encode(hmac_code))

    return {"timestamp": timestamp, "sign": sign}


def get_subscribe() -> str:
    """
    可通过内网访问已部署的项目接口获取订阅，返回字符串形式的明文订阅链接
    :return:
    """

    return "A shareLink of the V2RayCloudSpider server."


def quick_start(secret_key: str, access_token: str):
    """
    一个快速创建的demo
    :param secret_key: see https://developers.dingtalk.com/document/robots/customize-robot-security-settings
    :param access_token: see https://developers.dingtalk.com/document/robots/custom-robot-access
    :return:
    """
    # 获取订阅
    subscribe = get_subscribe()

    # 安全组：计算时间戳和应用签名
    security_group = calculate_the_signature(secret_key=secret_key)

    # 通过post机器人接口发送订阅
    ding_to_group(
        subscribe=subscribe,
        access_token=access_token,
        timestamp=security_group['timestamp'],
        sign_=security_group['sign']
    )


if __name__ == '__main__':
    quick_start(
        secret_key="",
        access_token=""
    )

```
<span id="demo"></span>
## 运行结果

<img width="543" alt="Snipaste_2021-08-31_02-07-19" src="https://user-images.githubusercontent.com/62018067/131385471-70422184-7b8c-4168-8366-e53b651370fc.png">

**Comment by wanghaisheng** [comment]
nb 我基本上是个代码白痴

**Comment by QIN2DIM** [comment]
@wanghaisheng 能出日志说明chromedriver配置是对的，系统读不到项目路径文件会根据环境变量找。

run 启动采集器
get 获取采集器输出（默认送到redis）
detach 分离采集器 （暂停实例，释放内存）

timeout error是因为部分采集器需要流量过墙，直接使用大陆ip访问会被拒绝（详见项目GeoIP）。挂个系统代理跑就不会就没问题了。或者项目部署在国外实体上也行。

如果只用general功能（在配置文件设置），的确只会是自动注册，目前的监控范围大概是暴露在公网上的所有SSPanel-uim站点，大概有300家[mining](https://github.com/QIN2DIM/V2RayCloudSpider/issues/28)

**Comment by wanghaisheng** [comment]
我昨晚突发奇想
@QIN2DIM 
github不是有个action可以跑脚本吗  client的话 非window平台  是不是直接可以用这个action
1.fork本仓库 
2.新建或者复制workflow的yml
3.手动或自动运行yml 
当然频次你要控制 就跟windows一样 10s一次？最多
4.运行结果保存在repo目录下  txt/csv文件？
整个流程下来 就完全脱离了平台限制 还能充分利用github

**Comment by QIN2DIM** [comment]
> 我昨晚突发奇想
> @QIN2DIM
> github不是有个action可以跑脚本吗 client的话 非window平台 是不是直接可以用这个action
> 1.fork本仓库
> 2.新建或者复制workflow的yml
> 3.手动或自动运行yml
> 当然频次你要控制 就跟windows一样 10s一次？最多
> 4.运行结果保存在repo目录下 txt/csv文件？
> 整个流程下来 就完全脱离了平台限制 还能充分利用github

感谢建议昂，利用`GithubActions`优异的性能确实能解决一些繁琐的操作节约开发成本。

早在去年项目需求分析以及技术选型阶段- -本人认为本项目开源版本应是一个脚本项目而非工程项目，或者说应是一个低门槛的最小优化部署模型- -看`.py`去掉注释也才五六千行代码，代码覆盖率才`~35%`就知道问题的严重性了。

同时也有很多更加适合国内网络环境的比`GithubActions`更加便捷地CI/CD解决方案，但考虑种种原因最终都没挂载。

白嫖说难听点就是偷，如果还把“薅羊毛”做成全球流通人手一个还能一键上云的垂搜引擎那还得了，完整服务几乎每台虚拟机每秒钟都有几百个协程在运行，估计用不了多久就没有免费的节点可用了Orz。

**Comment by wanghaisheng** [comment]
@QIN2DIM  的确是
那我不是要自己去selenium注册帐号了 哭

**Comment by QIN2DIM** [comment]
@wanghaisheng  
emmm，其实完全可以自己拉一个私有仓库部署Actions，但是配置文件的索引逻辑需要更改，弄成环境变量读取的方式，并把隐私信息存储到github `SECRET KEY` 环境变量中。

此外，不建议直接把采集结果写到repo仓库中...也许有更好的通信方式，比如机器人消息转发，或者邮件通信。
